services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 9020:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker/dockge:/app/data
      - /data/docker-compose:/data/docker-compose
    environment:
      - DOCKGE_STACKS_DIR=/data/docker-compose
